package com.ikaroorg.decision_wheel.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF2664EB)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF1055CA)
val OnPrimaryContainer = Color(0xFFFFFFFF)
val Secondary = Color(0xFF14B8A6)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFCCFBF1)
val OnSecondaryContainer = Color(0xFF0F766E)
val Tertiary = Color(0xFF1E40AF)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFDBEAFE)
val OnTertiaryContainer = Color(0xFF1E3A8A)
val Background = Color(0xFFF9F9F9)
val OnBackground = Color(0xFF111827)
val Surface = Color(0xFFFFFFFF)
val OnSurface = Color(0xFF111827)
val SurfaceVariant = Color(0xFFF3F3F3)
val OnSurfaceVariant = Color(0xFF6B7280)
val Outline = Color(0xFFE5E7EB)
val OutlineVariant = Color(0xFFECECEC)
val TextPrimary = Color(0xFF111827)
val TextSecondary = Color(0xFF6B7280)
val TextDisabled = Color(0xFF9CA3AF)
val Error = Color(0xFFDC2626)
val OnError = Color(0xFFFFFFFF)
val Success = Color(0xFF16A34A)
val OnSuccess = Color(0xFFFFFFFF)
val Warning = Color(0xFFD97706)
val OnWarning = Color(0xFFFFFFFF)
val BackgroundDark = Color(0xFF0F172A)
val OnBackgroundDark = Color(0xFFF8FAFC)
val SurfaceDark = Color(0xFF1E293B)
val OnSurfaceDark = Color(0xFFF8FAFC)
val SurfaceVariantDark = Color(0xFF1E293B)
val OnSurfaceVariantDark = Color(0xFF94A3B8)
val OutlineDark = Color(0xFF334155)